name: Build

env:
  QMK_BRANCH: firmware22

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: |
          git clone -b $QMK_BRANCH https://github.com/zsa/qmk_firmware.git
          ls -a
          ls qmk_firmware
          cp -r moonlander_brtcst qmk_firmware/moonlander_brtcst
          make -C qmk_firmware
          cd qmk_firmware && qmk setup -y

      - uses: actions/upload-artifact@v3
        with:
          name: moonlander_brtcst.bin
          path: qmk_firmware/.build/moonlander_brtcst.bin
          retention-days: 3
