name: Build

env:
  QMK_BRANCH: firmware22

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo apt install -y git python3-pip
          python3 -m pip install --user qmk
          qmk setup zsa/qmk_firmware -b $QMK_BRANCH -y -H ./qmk_firmware
          mkdir qmk_firmware/keyboards/moonlander/keymaps/brtcst
          cp -r moonlander_brtcst qmk_firmware/keyboards/moonlander/keymaps/brtcst
          cd qmk_firmware
          make moonlander:brtcst

      - uses: actions/upload-artifact@v3
        with:
          name: moonlander_brtcst.bin
          path: qmk_firmware/.build/moonlander_brtcst.bin
          retention-days: 3
